<a href="https://colab.research.google.com/github/julianramirez19m/hyperblog/blob/main/creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
print(np.array(my_list))

[1 2 3 4 5]


In [ ]:
print(np.random.rand(2,2))

[[0.05843797 0.92003014]
 [0.78016707 0.85252878]]


In [1]:
 import numpy as np

In [2]:
list(range(0,10)) #dato inicial 0 y dato stop es 10

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,10)  #Este método de NumPy nos permite generar arrays sin definir previamente una lista.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,20,2) #el dato inicial es 0, el dato de stop es 20 y el step es 2 que va a dar la lista de 2 en 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
np.zeros((5,5)) # Nos permite definir estructuras o esquemas mediante 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((5,5)) # Nos permite definir estructuras o esquemas mediante 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.linspace(0,10,5) #Permite generar una array definiendo un inicio, un final y cuantas divisiones tendrá.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.eye(5) #También podemos crear una matriz con una diagonal de 1 y el resto de 0.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand() #Otro método importante es generar números aleatorios.

0.12748729313938778

In [10]:
np.random.rand(4) #También se pueden generar vectores.

array([0.02755904, 0.97669795, 0.144522  , 0.96917334])

In [11]:
np.random.rand(4,5) #Tambien se pueden generar matrices

array([[0.14946898, 0.94716118, 0.94419444, 0.52473753, 0.76456832],
       [0.99249217, 0.14494074, 0.43951948, 0.49174488, 0.98215523],
       [0.85775742, 0.88215255, 0.50617518, 0.78474297, 0.05000221],
       [0.02726182, 0.66547966, 0.5809529 , 0.28121312, 0.66033028]])

In [14]:
np.random.randint(0,30) #NumPy nos permite también generar números enteros En este caso números enteros entre el 1 y 30

6

In [16]:
np.random.randint(0,30,(3,3)) #También podemos llevarlos a una estructura definida.

array([[ 4, 26, 19],
       [21, 12,  6],
       [24,  6, 26]])